### ISSUE TITLE
myMPD v12.0.0 can't enumerate candidates output to move to a new partition

### ISSUE THREAD

**Issue by tsunulukai** [jcorporation/myMPD#1106]
myMPD version: 12.0.0

**Describe the bug**

After upgrading to myMPD 12.0.0, myMPD is unable to enumerate outputs that can be moved to a new partition.
When downgrading back to myMPD 11.0.0, the enumeration works fine again.

**To Reproduce**

1. Create new partition
2. Switch to new partition
3. Try to move outputs to the new partition: the list of outputs is empty, although it should not.

**Screenshots**

myMPD 11.0.0 (working as expected):
![image](https://github.com/jcorporation/myMPD/assets/4215150/35883171-41b3-4757-a51d-e8777bc906a8)

myMPD 12.0.0 (empty list of outputs):
![image](https://github.com/jcorporation/myMPD/assets/4215150/d3c96421-c0d1-4189-a15c-6a716b499c76)

Possibly related error visible in notifications:
![image](https://github.com/jcorporation/myMPD/assets/4215150/ec4356c5-2fa6-4288-8768-862e6500b61d)

*** API Logs ***

In both version, when opening the list of candidates outputs to move, here's the trace from the API request.
So I suppose the issue lies in the processing of the response, as the API response send the complete list of outputs both for myMPD v11.0.0 & v12.0.0

1. POST https://nas/myMPD/api/default
```
REQ:
{
	"id": 988493032,
	"jsonrpc": "2.0",
	"method": "MYMPD_API_PLAYER_OUTPUT_LIST",
	"params": {}
}
RESP:
{
	"jsonrpc": "2.0",
	"id": 988493032,
	"result": {
		"method": "MYMPD_API_PLAYER_OUTPUT_LIST",
		"data": [
			{
				"id": 0,
				"name": "MultiRoom",
				"state": 0,
				"plugin": "pulse"
			},
			{
				"id": 1,
				"name": "Multimedia",
				"state": 0,
				"plugin": "pulse"
			},
			{
				"id": 2,
				"name": "Saloon",
				"state": 0,
				"plugin": "pulse"
			},
			{
				"id": 3,
				"name": "ShowRoom",
				"state": 0,
				"plugin": "pulse"
			},
			{
				"id": 4,
				"name": "Attic",
				"state": 0,
				"plugin": "pulse"
			},
			{
				"id": 5,
				"name": "Bathroom",
				"state": 0,
				"plugin": "pulse"
			},
			{
				"id": 6,
				"name": "HTTP Stream",
				"state": 0,
				"plugin": "httpd"
			}
		],
		"partition": "default",
		"numOutputs": 7
	}
}
```

2. POST	https://nas/myMPD/api/Test
```
REQ:
{
	"id": 988493033,
	"jsonrpc": "2.0",
	"method": "MYMPD_API_PLAYER_OUTPUT_LIST",
	"params": {}
}

{
	"jsonrpc": "2.0",
	"id": 988493033,
	"result": {
		"method": "MYMPD_API_PLAYER_OUTPUT_LIST",
		"data": [],
		"partition": "Test",
		"numOutputs": 0
	}
}
```

**Server plattform (please complete the following information):**
 - OS: Debian
 - OS version 12.1 (Bookworm)
 - Plattform: x86_64
 - MPD version: 0.24 beta

**Client plattform (please complete the following information):**
Same error on Windows 11 (Firefox/Edge) & Android (Firefox/Brave)

**Comment by jcorporation** [comment]
Thanks for the detailed bug report. A found to bugs in the switch partition output functions. Should be fixed in devel, can you please test?

**Comment by tsunulukai** [comment]
Hello, just recompiled and tested again after purging the application cache. Same issue...

In the browser's debug console I get this error:

```
Uncaught TypeError: uiElements.modalPartition is undefined
    switchPartition https://nas/myMPD/js/combined.js:13
    initModalPartitions https://nas/myMPD/js/combined.js:13
```

When clicking on the "move output to this partition", I still get two API requests sent to myMPD and responses are still as shown in my previous message.


Possibly noteworthy element: I'm running myMPD behind an nginx reverse proxy. When accessing it without the reverse proxy, I still have the same issue, so I don't think nginx is at fault here.

When accessing myMPD without the nginx proxy, I get this output in the console:
```
Uncaught TypeError: uiElements.modalPartition is undefined
    switchPartition http://nas:880/js/combined.js:13
    initModalPartitions http://nas:880/js/combined.js:13
    initModalPartitions http://nas:880/js/combined.js:13
    appInit http://nas:880/js/combined.js:13
    appInitStart http://nas:880/js/combined.js:13
    checkAPIresponse http://nas:880/js/combined.js:13
    sendAPIpartition http://nas:880/js/combined.js:13
    sendAPI http://nas:880/js/combined.js:13
    appInitStart http://nas:880/js/combined.js:13
    <anonymous> http://nas:880/js/combined.js:13
[combined.js:13:205120](http://nas:880/js/combined.js)
    switchPartition http://nas:880/js/combined.js:13
    initModalPartitions http://nas:880/js/combined.js:13
    (Async: EventListener.handleEvent)
    initModalPartitions http://nas:880/js/combined.js:13
    appInit http://nas:880/js/combined.js:13
    appInitStart http://nas:880/js/combined.js:13
    checkAPIresponse http://nas:880/js/combined.js:13
    sendAPIpartition http://nas:880/js/combined.js:13
    InterpretGeneratorResume self-hosted:1469
    AsyncFunctionNext self-hosted:852
    (Async: async)
    sendAPI http://nas:880/js/combined.js:13
    appInitStart http://nas:880/js/combined.js:13
    <anonymous> http://nas:880/js/combined.js:13
```

Are you able to reproduce this issue ?

**Comment by jcorporation** [comment]
https://github.com/jcorporation/myMPD/commit/f244ebf8056f65ca7308546866dc2e3c2b38b105 should fix exactly this issue.

With master I could reproduce this issue and I validated the fix in devel.

**Comment by tsunulukai** [comment]
Strange, I built from 69898a630e90cef91541d056d1ae4ac67378e7e2 and still have the problem.
```
/srv/WorkDir/builder/myMPD# git log
commit 69898a630e90cef91541d056d1ae4ac67378e7e2 (HEAD -> devel, origin/devel)
Author: jcorporation <mail@jcgames.de>
Date:   Sat Sep 16 00:14:25 2023 +0200

    Upd: changelog

commit 150d78155e32f0acb1d6d0cb64437fc2ca7294aa
Author: jcorporation <mail@jcgames.de>
Date:   Sat Sep 16 00:10:33 2023 +0200

    Fix: remove global object #1106

commit e17162acf9ec1620ea1f9aad5e3adf1f2b3a5011
Author: jcorporation <mail@jcgames.de>
Date:   Sat Sep 16 00:01:19 2023 +0200

    Fix: listing of outputs to move to current partition #1106
```

Purging the myMPD cache, using private mode to ensure I'm not still using outdated cached elements doesn't change it...

I'll try building again just to be sure I haven't missed something.

**Comment by jcorporation** [comment]
I rechecked current devel with release build and it works in my environment.

**Comment by tsunulukai** [comment]
I just rebuilt from a fresh source tree and I can confirm it works back again, indeed.
Thanks for the jumping on the ball so fast & resolving it !

**Comment by tsunulukai** [comment]
nb: when I pull a new version, I usually do

```
git pull
./build.sh createassets
./build.sh sbuild_build
```

but it seems doing so in this case resulted in the incorrect js file being packaged in the resulting .deb package... 
should I do a `./build cleanup` beforehand ?
