### ISSUE TITLE
Wrong elements per page count in filesystem view

### ISSUE THREAD

**Issue by therion23** [jcorporation/myMPD#1168]
11.0.4 master, the rest is as yesterday. Firefox/Linux and Edge/Win 11.

When using filesystem view, the first page of results always shows one less than the "elements per page" value is set to on the top right page dropdown. I.e., if set to 100, the first page will only show 99 rows, but the following pages show 100.

A side effect is if a folder has, say, 25 files and the elements count is set to 25, it is impossible to show the final track.

Changing the setting in Appearance has no effect.

**Comment by jcorporation** [comment]
You mean v13.0.4? I can not reproduce it. Can you attach a screenshot that illustrates it and the response for the MYMPD_API_DATABASE_FILESYSTEM_LIST API request from the browser developer tools?

**Comment by therion23** [comment]
Yes, i mean 13.0.4 of course, my bad. And ".." looks unrelated, since it is there on every page:

<img width="949" alt="Screenshot 2023-11-11 172011" src="https://github.com/jcorporation/myMPD/assets/13167467/a8ff4862-da51-4d04-a1ca-dc65e5c75134">
<img width="947" alt="Screenshot 2023-11-11 172201" src="https://github.com/jcorporation/myMPD/assets/13167467/5093ac00-8366-4661-8af0-6ccbb846293c">

Let me know how to make that API call if you still need it.

**Comment by therion23** [comment]
Here is a case where the number of files match the number per page - clicking the right "1" top right has no effect.

<img width="946" alt="Screenshot 2023-11-11 172639" src="https://github.com/jcorporation/myMPD/assets/13167467/41a921a5-6ddc-4bb3-b11f-ed6ee6812208">

**Comment by jcorporation** [comment]
Screenshorts shows the correct number of elements, 24 cds + 1 parent element = 25.  The total number of entries is not correctly calculated, this is fixed with fe0bda617c790b18d7b360488cfb42e8a9c02f62.

**Comment by jcorporation** [comment]
Above commit should fix it. Can you test?

**Comment by therion23** [comment]
The count is now consistent across page 1 and the following ones. However, if the track count matches the elements count (as in the last screenshot), all 50 rows are now shown, but i get a page selector looking like this, with a clickable page 2 that is empty:

![2023-11-11-175511_363x159_scrot](https://github.com/jcorporation/myMPD/assets/13167467/07a8d1d8-9389-4d9b-b967-17bc23fbe831)

**Comment by jcorporation** [comment]
My bad, that comes from the conditionally insert of the parent dir element, I must refactor this...

**Comment by jcorporation** [comment]
Last commit fixes all that issues. myMPD simply does not insert any parent dir entry anymore. Most other filesystem browser behave the same.

**Comment by therion23** [comment]
Works like a charm. And considering there is both the "address bar" and the optional "back" button, i hope nobody will miss it.

I still get this popup when the number of entries are equal to or less than the elements per page setting:

![2023-11-11-200628_349x155_scrot](https://github.com/jcorporation/myMPD/assets/13167467/cc90081e-64c9-4df7-8414-8676c3f20983)

Choosing either just makes the popup disappear - or, hard to say, since it's supposed to show the same page i came from.

**Comment by jcorporation** [comment]
I think removing the .. entry makes the interface cleaner. The behavior of the page select dropdown is as designed. It could be optimized, but this is an other topic. Closing this bug now.

**Comment by therion23** [comment]
All right, thank you and good job!
