### ISSUE TITLE
Getting Javascript error after having interface open for a while

### ISSUE THREAD

**Issue by aereaux** [jcorporation/myMPD#902]
myMPD version: 10.1.2-1

**Describe the bug**

After having the interface open for a while (not really sure what exactly triggers it), I start getting this JS error repeatedly:
JavaScript error: SyntaxError: Element.querySelector: '[data-tag=-]' is not a valid selector (https://server2.jmad.org/mympd/js/combined.js: 8)
This is the URL I am on when it happens, and it's repeatable when using this URL: `<mympd>/#%7B%22card%22%3A%22Queue%22%2C%22tab%22%3A%22Current%22%2C%22offset%22%3A0%2C%22limit%22%3A500%2C%22filter%22%3A%22-%22%2C%22sort%22%3A%7B%22tag%22%3A%22-%22%2C%22desc%22%3Afalse%7D%2C%22tag%22%3A%22-%22%2C%22search%22%3A%22%22%7D`

**To Reproduce**

1. Leave it open and playing for a while.
2. URL looks something like this: `<mympd>/#%7B%22card%22%3A%22Queue%22%2C%22tab%22%3A%22Current%22%2C%22offset%22%3A0%2C%22limit%22%3A500%2C%22filter%22%3A%22-%22%2C%22sort%22%3A%7B%22tag%22%3A%22-%22%2C%22desc%22%3Afalse%7D%2C%22tag%22%3A%22-%22%2C%22search%22%3A%22%22%7D`
3. Going to above url directly triggers it too.
6. See error, and repeats on song change or interacting with some elements.

**Expected behavior**

No error.

**Screenshots**

**Server plattform (please complete the following information):**
 - OS: Arch Linux
 - OS version: Rolling, current
 - Plattform: x86_64
 - MPD version: 0.23.10-2

**Client plattform (please complete the following information):**
 - Device: Desktop
 - OS: Arch Linux
 - Browser: Firefox
 - Browser version: 107.0-1

**Debug logs (please attach if it can be useful)**

Look at https://jcorporation.github.io/myMPD/debug

 - myMPD debug log
 - MPD verbose log
 - Browser error console
```
Content Security Policy: Couldn’t process unknown directive ‘require-trusted-types-for’
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:42:9
ERROR: JavaScript error: SyntaxError: Element.querySelector: '[data-tag=-]' is not a valid selector (https://server2.jmad.org/mympd/js/combined.js: 8) combined.js:8:19322
    logLog https://server2.jmad.org/mympd/js/combined.js:8
    logError https://server2.jmad.org/mympd/js/combined.js:8
    onerror https://server2.jmad.org/mympd/js/combined.js:8
```
 - Browser network console

 
**Configuration (please attach if it can be useful)**

 - tarball of /var/lib/mympd/state (``tar -cf mympd_state.tar /var/lib/mympd/state``)
 - tarball of /var/lib/mympd/config (``tar -cf mympd_config.tar /var/lib/mympd/config``)
 - `mpd.conf` 

**Additional context**

Let me know if any other debugging info would be helpful.

**Comment by jcorporation** [comment]
URL decoded the hash looks like:
```
<mympd>/#{"card":"Queue","tab":"Current","offset":0,"limit":500,"filter":"-","sort":{"tag":"-","desc":false},"tag":"-","search":""}
```

The filter value is `-`, this is invalid. It should be `any` or a valid mpd tag. I am unsure what causes this.

![image](https://user-images.githubusercontent.com/765844/203425445-c7afb214-ba44-465c-a140-ff55e254b6d3.png)

This dropdown should show no selection in your error case. Select e.g. 'Any Tag' to change the filter, this should fix the error.

Could it be a bookmark for a older myMPD version?

**Comment by aereaux** [comment]
I don't think it's anything from an older version.  To fix it I generally clear out everything except the base mympd url and then eventually I get back into this error case.  I've been trying to determine what circumstances lead to it, but it happens pretty irregularly.

**Comment by jcorporation** [comment]
Any news?

**Comment by aereaux** [comment]
I have not had any luck figuring out what causes this problem, I'll update if I figure it out.  The workaround you proposed works a lot better than anything I was using before when I encounter it, though

**Comment by aereaux** [comment]
After a bit of further testing it could be related to playing an item that doesn't have an album?  It still doesn't happen consistently but it seems like it happens more often after that.
